import Layout from "@/components/Layout";
import { Card } from "@/components/ui/card";
import { Link } from "wouter";

export default function Disclaimer() {
  return (
    <Layout>
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-primary mb-2">Investment Disclaimer</h1>
          <div className="h-0.5 w-24 bg-accent mx-auto mb-4 mt-3"></div>
          <p className="text-xs text-muted-foreground">Last Updated: January 2026</p>
        </div>

        <Card className="p-6 prose prose-sm max-w-none dark:prose-invert prose-headings:text-base prose-headings:font-semibold prose-p:text-[13px] prose-p:leading-relaxed prose-li:text-[13px] prose-li:leading-relaxed">
          <h2 className="text-primary">Important Notice</h2>
          <p className="text-foreground">
            RE Data Metrix ("RDM") provides analytical tools and educational resources designed to assist real estate investors in evaluating potential investment opportunities. The information and analysis provided through our platform are intended for informational and educational purposes only.
          </p>

          <h2 className="text-primary">Not Financial, Legal, or Investment Advice</h2>
          <p className="text-foreground">
            The content, tools, and analyses provided by RE Data Metrix do not constitute financial, legal, tax, or investment advice. The platform is not intended to replace the services of qualified professionals, and users should consult with licensed attorneys, accountants, financial advisors, and other appropriate professionals before making any investment decisions.
          </p>

          <h2 className="text-primary">No Guarantees of Accuracy</h2>
          <p className="text-foreground">
            While we strive to provide accurate and up-to-date information, RE Data Metrix makes no warranties or representations regarding the accuracy, completeness, or reliability of any information, calculations, or analysis generated by the platform. Property values, rental estimates, rehabilitation costs, and other data may be based on third-party sources, historical data, or user inputs that may not reflect current market conditions.
          </p>

          <h2 className="text-primary">Investment Risks</h2>
          <p className="text-foreground">
            Real estate investment involves significant risks, including but not limited to:
          </p>
          <ul className="text-foreground">
            <li>Market fluctuations that may affect property values</li>
            <li>Unexpected repair or rehabilitation costs</li>
            <li>Changes in interest rates affecting financing costs</li>
            <li>Vacancy periods and tenant-related issues</li>
            <li>Regulatory changes affecting property use or taxation</li>
            <li>Economic downturns affecting rental income and property values</li>
            <li>Environmental or structural issues not discovered during due diligence</li>
          </ul>
          <p className="text-foreground">
            Past performance of any investment strategy does not guarantee future results. Users should conduct their own due diligence and carefully assess their risk tolerance before making any investment decisions.
          </p>

          <h2 className="text-primary">Hypothetical Projections</h2>
          <p className="text-foreground">
            The deal analyses and projections generated by our platform are hypothetical in nature. They are based on assumptions, user inputs, and estimated data that may not accurately reflect actual outcomes. Actual results may vary significantly from projected returns due to factors beyond our control or prediction.
          </p>

          <h2 className="text-primary">Third-Party Information</h2>
          <p className="text-foreground">
            RE Data Metrix may utilize data from third-party sources, including property databases, market analytics providers, and public records. We do not verify the accuracy of third-party information and are not responsible for errors or omissions in data provided by external sources.
          </p>

          <h2 className="text-primary">Lender Information</h2>
          <p className="text-foreground">
            Information about loan products, terms, and lenders displayed on our platform is provided for comparison purposes only. Actual loan terms, rates, and availability may vary based on individual circumstances, creditworthiness, and lender requirements. RE Data Metrix does not guarantee loan approval or specific terms.
          </p>

          <h2 className="text-primary">User Responsibility</h2>
          <p className="text-foreground">
            Users are solely responsible for verifying all information, conducting independent research, and making their own investment decisions. By using RE Data Metrix, you acknowledge that you understand and accept the risks associated with real estate investment and that you will not rely solely on our platform for investment decisions.
          </p>

          <h2 className="text-primary">Limitation of Liability</h2>
          <p className="text-foreground">
            To the fullest extent permitted by law, RE Data Metrix, its officers, directors, employees, agents, and affiliates shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages arising from or related to your use of the platform, reliance on any information provided, or any investment decisions made based on such information.
          </p>

          <h2 className="text-primary">Contact Us</h2>
          <p className="text-foreground">
            If you have questions about this disclaimer or our services, please contact us through our <Link href="/contact" className="text-primary hover:underline">Contact page</Link> or review our <Link href="/terms" className="text-primary hover:underline">Terms of Service</Link> and <Link href="/privacy" className="text-primary hover:underline">Privacy Policy</Link> for additional information.
          </p>
        </Card>
      </div>
    </Layout>
  );
}
